In [29]:
import pandas as pd
import numpy as np
import pickle

In [30]:
dataset=pd.read_csv('insurance_pre.csv')
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [32]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [33]:
preinput=sc.transform([[18,33.770,1,1,0]])

In [34]:
preinput

array([[-1.5330973 ,  0.48419605, -0.06746417,  1.02378711, -0.50466988]])

In [35]:
loaded_model=pickle.load(open('finalized_model_rf.sav','rb'))
result=loaded_model.predict(preinput)

C:\Anaconda3\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


In [36]:
result

array([-0.85889078])

In [37]:
preoutput=scy.inverse_transform([result])

In [38]:
preoutput

array([[3034.65144153]])